spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodieDb?useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  jpa:
   hibernate.ddl-auto: update
   generate-ddl: true
   show-sql: true
   database: MYSQL
   database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  port: 9000
  
